export const SHOW_DOCTOR_MODEL = "SHOW_DOCTOR_MODEL";
export const SHOW_DOCTOR_EDIT_MODEL = "SHOW_DOCTOR_EDIT_MODEL";
export const SHOW_DOCTOR_INFO_MODEL = "SHOW_DOCTOR_INFO_MODEL";
export const UPDATE_DOCTORS = "UPDATE_DOCTORS";
export const SET_CURRENT_DOCTOR = "SET_CURRENT_DOCTOR";
export const UPDATE_DOCTOR_STATUS = "UPDATE_DOCTOR_STATUS";